import type { Event } from './types';

export const events: Event[] = [
  {
    id: 'event-1',
    name: 'Annual Tech Summit 2024',
    date: '2024-08-15',
    location: 'Silicon Valley Convention Center',
    description: 'The biggest tech summit of the year, featuring talks from industry leaders and innovators.',
    imageUrl: 'https://picsum.photos/600/400',
    dataAiHint: 'tech conference',
    registrations: 450,
    targetRegistrations: 500,
    checkedIn: 410,
    feedback: [5, 5, 4, 5, 4, 4, 5, 3, 5],
    deadline: '2024-08-01T23:59:59Z',
  },
  {
    id: 'event-2',
    name: 'Creative Coders Workshop',
    date: '2024-09-10',
    location: 'Online',
    description: 'A hands-on workshop for developers interested in generative art and creative coding.',
    imageUrl: 'https://picsum.photos/600/400',
    dataAiHint: 'code workshop',
    registrations: 85,
    targetRegistrations: 100,
    checkedIn: 80,
    feedback: [5, 5, 5, 4, 5, 5],
    deadline: '2024-09-01T23:59:59Z',
  },
  {
    id: 'event-3',
    name: 'Startup Pitch Night',
    date: '2024-09-25',
    location: 'Innovation Hub Downtown',
    description: 'An exciting evening where the brightest new startups pitch their ideas to investors.',
    imageUrl: 'https://picsum.photos/600/400',
    dataAiHint: 'startup pitch',
    registrations: 120,
    targetRegistrations: 200,
    checkedIn: 95,
    feedback: [4, 3, 4, 5, 3, 4, 4],
    deadline: '2024-09-20T23:59:59Z',
  },
  {
    id: 'event-4',
    name: 'AI in Healthcare Symposium',
    date: '2024-10-05',
    location: 'Grand Hospital Auditorium',
    description: 'Exploring the latest advancements and ethical considerations of AI in the medical field.',
    imageUrl: 'https://picsum.photos/600/400',
    dataAiHint: 'medical conference',
    registrations: 70,
    targetRegistrations: 150,
    checkedIn: 55,
    feedback: [5, 4, 5, 5, 4],
    deadline: '2024-09-28T23:59:59Z',
  },
  {
    id: 'event-5',
    name: 'Future of Gaming Expo',
    date: '2024-11-20',
    location: 'Metropolis Expo Center',
    description: 'Get a first look at the next generation of gaming hardware and software.',
    imageUrl: 'https://picsum.photos/600/400',
    dataAiHint: 'gaming expo',
    registrations: 25,
    targetRegistrations: 1000,
    checkedIn: 10,
    feedback: [],
    deadline: '2024-11-15T23:59:59Z',
  },
];
